# Generated by nixos-generate-config --no-filesystems --root /mnt
# Replace this file with the actual output during installation.
{
  modulesPath,
  inputs,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    # Generic hardware profiles from nixos-hardware. common-gpu-amd is the
    # main win here — enables amdgpu in initrd for smoother boot. The other
    # two are mkDefault stubs that match what we already set manually.
    inputs.nixos-hardware.nixosModules.common-cpu-amd
    inputs.nixos-hardware.nixosModules.common-gpu-amd
    inputs.nixos-hardware.nixosModules.common-pc-ssd
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage"];
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    kernelModules = ["kvm-amd"];
  };

  hardware.amd-custom = {
    enable = true;
    enableOpenCL = true;
    enableCorectrl = true;
  };

  hardware = {
    enableRedistributableFirmware = true;

    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
  };
}
