# Generated by nixos-generate-config --no-filesystems --root /mnt
# Replace this file with the actual output during installation.
{
  lib,
  config,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware.amd-custom = {
    enable = true;
    enableOpenCL = true;
    enableCorectrl = true;
  };

  hardware = {
    enableRedistributableFirmware = true;
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
  };
}
