---
name: Check Flakes
on:
  pull_request:
    branches:
      - main

env:
  OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
  OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}

jobs:
  check_flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: 1password/load-secrets-action/configure@92467eb28f72e8255933372f1e0707c567ce2259  # v4
        with:
          connect-host: ${{ env.OP_CONNECT_HOST }}
          connect-token: ${{ env.OP_CONNECT_TOKEN }}

      - uses: 1password/load-secrets-action@92467eb28f72e8255933372f1e0707c567ce2259  # v4
        with:
          export-env: true
        env:
          BOT_APP_ID: op://homelab/GITHUB/GITHUB_APP_ID
          BOT_APP_PRIVATE_KEY: op://homelab/GITHUB/GITHUB_APP_PRIVATE_KEY

      - name: Generate Token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3  # v3.1.1
        id: app-token
        with:
          app-id: "${{ env.BOT_APP_ID }}"
          private-key: "${{ env.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe  # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix flake check
